// Generated by scripts/build-site-data.mjs. Do not edit by hand.
globalThis.SITE_DATA = {
  "blocks": [
    {
      "section": "Block",
      "blockType": "mode",
      "sourceKind": "Mode",
      "key": "mode.explore",
      "aliases": [],
      "title": "Explore",
      "summary": "Use when the problem is still underframed.",
      "tags": [
        "explore"
      ],
      "copy": "Enter EXPLORE mode.\nGenerate multiple plausible directions instead of converging too early.\nSurface unknowns and contrasting options.\nDo not choose yet unless I explicitly ask you to.",
      "body": [
        [
          "Use when",
          "the problem is still underframed, you need options before decisions, premature narrowing is the main risk"
        ],
        [
          "Optimizes for",
          "breadth, variety, alternative framings, surfaced unknowns"
        ],
        [
          "Suppresses",
          "early commitment, single-path planning, fake certainty"
        ],
        [
          "Exit when",
          "repeated patterns appear, a shortlist exists, the next step is comparison or choice"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "modes/explore/README.md"
    },
    {
      "section": "Block",
      "blockType": "mode",
      "sourceKind": "Mode",
      "key": "mode.decide",
      "aliases": [],
      "title": "Decide",
      "summary": "Use when real options already exist.",
      "tags": [
        "decide"
      ],
      "copy": "Enter DECIDE mode.\nCompare the available options against explicit criteria.\nChoose the best current option, state tradeoffs, and name the next action.\nDo not expand the option set unless it is clearly too weak to decide from.",
      "body": [
        [
          "Use when",
          "real options already exist, criteria can be stated, the main risk is drifting instead of choosing"
        ],
        [
          "Optimizes for",
          "commitment, explicit tradeoffs, best current choice, action readiness"
        ],
        [
          "Suppresses",
          "unnecessary expansion, vague comparisons, endless hedge language"
        ],
        [
          "Exit when",
          "a choice is made, uncertainty is named, a next action is clear"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "modes/decide/README.md"
    },
    {
      "section": "Block",
      "blockType": "mode",
      "sourceKind": "Mode",
      "key": "mode.critique",
      "aliases": [],
      "title": "Critique",
      "summary": "Use when a draft, plan, or decision already exists.",
      "tags": [
        "critique"
      ],
      "copy": "Enter CRITIQUE mode.\nInspect the current artifact for weaknesses, blind spots, and likely failure points.\nPrioritize the highest-leverage findings and give concrete revision advice.\nDo not soften the critique with filler praise.",
      "body": [
        [
          "Use when",
          "a draft, plan, or decision already exists, missing flaws would be costly, you want revision guidance, not reassurance"
        ],
        [
          "Optimizes for",
          "defect detection, blind spot exposure, sharper revision targets"
        ],
        [
          "Suppresses",
          "vague praise, politeness masking substance, unprioritized commentary"
        ],
        [
          "Exit when",
          "the most important weaknesses are visible, revision advice is concrete"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "modes/critique/README.md"
    },
    {
      "section": "Block",
      "blockType": "mode",
      "sourceKind": "Mode",
      "key": "mode.reflect",
      "aliases": [],
      "title": "Reflect",
      "summary": "Use when an outcome exists.",
      "tags": [
        "reflect"
      ],
      "copy": "Enter REFLECT mode.\nCompare what was expected with what actually happened.\nExtract reusable lessons and identify what should change in my prompts, stacks, or decisions next time.\nDo not stop at recap.",
      "body": [
        [
          "Use when",
          "an outcome exists, you can compare expectation versus reality, the main risk is repeating the same mistake"
        ],
        [
          "Optimizes for",
          "lesson extraction, system improvement, reusable adjustments"
        ],
        [
          "Suppresses",
          "empty retrospectives, blame without change, narrative recap with no lesson"
        ],
        [
          "Exit when",
          "at least one reusable lesson exists, at least one concrete adjustment is named"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "modes/reflect/README.md"
    },
    {
      "section": "Block",
      "blockType": "strategy",
      "sourceKind": "Strategy",
      "key": "strategy.problem-split",
      "aliases": [
        "strategy.problem_split"
      ],
      "title": "Problem Split",
      "summary": "Use when the task feels vague, tangled, or overloaded.",
      "tags": [
        "problem",
        "split"
      ],
      "copy": "Apply the PROBLEM SPLIT strategy.\nBreak this into distinct subproblems, surface open questions, and suggest the best order of attack.\nKeep the decomposition practical rather than exhaustive.",
      "body": [
        [
          "Use when",
          "the task feels vague, tangled, or overloaded, framing is the bottleneck"
        ],
        [
          "Helps prevent",
          "tackling the wrong subproblem, mixing framing, decision, and execution together, hidden dependencies staying invisible"
        ],
        [
          "How to use",
          "restate the problem, identify distinct subproblems, separate knowns from unknowns, identify which subproblem should be handled first"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "strategies/problem_split/README.md"
    },
    {
      "section": "Block",
      "blockType": "strategy",
      "sourceKind": "Strategy",
      "key": "strategy.premortem",
      "aliases": [
        "strategy.premortem"
      ],
      "title": "Premortem",
      "summary": "Use when a plan seems plausible but failure would matter.",
      "tags": [
        "premortem"
      ],
      "copy": "Apply the PREMORTEM strategy.\nAssume this plan failed. List the most plausible reasons why, prioritize the biggest risks, and suggest mitigations that would materially improve the plan before execution.",
      "body": [
        [
          "Use when",
          "a plan seems plausible but failure would matter, you want risk visibility before committing"
        ],
        [
          "Helps prevent",
          "optimism bias, hidden execution risks, plans that look fine on first read but fail in practice"
        ],
        [
          "How to use",
          "assume the plan failed, list the most plausible reasons why, prioritize the highest-leverage risks, add mitigations before execution"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "strategies/premortem/README.md"
    },
    {
      "section": "Block",
      "blockType": "strategy",
      "sourceKind": "Strategy",
      "key": "strategy.steelman",
      "aliases": [
        "strategy.steelman"
      ],
      "title": "Steelman",
      "summary": "Use when you are about to reject or override a position.",
      "tags": [
        "steelman"
      ],
      "copy": "Apply the STEELMAN strategy.\nArgue the strongest version of the position I am considering challenging.\nMake the case as well as its best proponent would.\nThen identify what would actually be required to defeat that strongest version.",
      "body": [
        [
          "Use when",
          "you are about to reject or override a position, you want to ensure you are defeating the best version of an argument, not a weaker caricature, you suspect your critique may be motivated rather than rigorous"
        ],
        [
          "Helps prevent",
          "attacking straw versions of opposing views, overconfident dismissal of alternatives, blind spots in your own position"
        ],
        [
          "How to use",
          "state the position you are considering challenging, argue it as strongly as possible — as its best proponent would, identify what evidence or reasoning would genuinely defeat that strongest version, proceed with critique only once you have met that bar"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "strategies/steelman/README.md"
    },
    {
      "section": "Block",
      "blockType": "strategy",
      "sourceKind": "Strategy",
      "key": "strategy.inversion",
      "aliases": [
        "strategy.inversion"
      ],
      "title": "Inversion",
      "summary": "Use when you want to find constraints that forward-planning misses.",
      "tags": [
        "inversion"
      ],
      "copy": "Apply the INVERSION strategy.\nDefine clearly what a bad outcome looks like for this situation.\nList the most plausible paths to that bad outcome.\nThen flip: what conditions would prevent each path?",
      "body": [
        [
          "Use when",
          "you want to find constraints that forward-planning misses, a plan or decision needs stress-testing before commitment, you suspect optimism bias is obscuring real failure modes"
        ],
        [
          "Helps prevent",
          "optimism blindness, underestimating how things go wrong, plans that ignore structural failure modes"
        ],
        [
          "How to use",
          "define the worst realistic outcome for this situation, enumerate the most plausible paths to that outcome, flip each path: what conditions would prevent it?, treat the flipped conditions as design constraints or mitigations"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "strategies/inversion/README.md"
    },
    {
      "section": "Block",
      "blockType": "strategy",
      "sourceKind": "Strategy",
      "key": "strategy.red-team",
      "aliases": [
        "strategy.red_team"
      ],
      "title": "Red Team",
      "summary": "Use when you have a plan you are inclined to proceed with.",
      "tags": [
        "red",
        "team"
      ],
      "copy": "Apply the RED TEAM strategy.\nArgue against this plan as a hostile critic whose goal is to defeat it.\nPrioritize arguments that are both credible and hard to dismiss.\nDo not soften the critique or suggest fixes until the attack is complete.",
      "body": [
        [
          "Use when",
          "you have a plan you are inclined to proceed with, you want to surface objections before committing, you suspect motivated reasoning may be shaping your evaluation"
        ],
        [
          "Helps prevent",
          "motivated reasoning, premature commitment, plans that have not been genuinely challenged"
        ],
        [
          "How to use",
          "shift to an adversarial frame — your goal is to defeat the plan, not improve it, generate the most damaging, credible attacks you can, prioritize attacks that are hard to dismiss, only after the attack is complete, judge which require a real response before proceeding"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "strategies/red_team/README.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Prompt Block",
      "key": "core.frame.task",
      "aliases": [
        "core.frame-task"
      ],
      "title": "Task Frame",
      "summary": "Use this prompt block to turn a messy request into a clean starting frame.",
      "tags": [
        "task",
        "frame"
      ],
      "copy": "Restate this raw request or situation as a structured problem frame.\n\nRequirements:\n\n- separate the stated ask from the likely objective\n- keep constraints literal\n- surface unknowns without pretending to resolve them\n- recommend the next reasoning move rather than a full solution\n\nReturn:\n\n- task\n- objective\n- constraints\n- knowns\n- unknowns\n- recommended next reasoning step\n\nInput:\n{paste raw request or situation}",
      "body": [
        [
          "Best use",
          "at the start of a stack, before selecting a strategy, before asking for options or plans"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "prompts/blocks/frame.task/prompt.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Prompt Block",
      "key": "core.frame.success-criteria",
      "aliases": [
        "core.frame-success-criteria"
      ],
      "title": "Success Criteria",
      "summary": "Use this prompt block when a task lacks clear standards.",
      "tags": [
        "success",
        "criteria",
        "frame"
      ],
      "copy": "Define explicit success criteria for this task, decision, or plan.\n\nRequirements:\n\n- separate must-haves from nice-to-haves\n- include at least one failure condition\n- name the hardest tradeoff to watch\n- keep the criteria concrete enough to judge later\n\nReturn:\n\n- must-haves\n- nice-to-haves\n- failure conditions\n- tradeoffs to watch\n\nInput:\n{paste target task, decision, or plan}",
      "body": [
        [
          "Best use",
          "before critique, before decision-making, before comparing alternatives"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "prompts/blocks/frame.success-criteria/prompt.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Prompt Block",
      "key": "core.guardrail.uncertainty",
      "aliases": [
        "core.guardrail-uncertainty"
      ],
      "title": "Uncertainty Guardrail",
      "summary": "Use this prompt block when the model might hide uncertainty.",
      "tags": [
        "uncertainty",
        "guardrail"
      ],
      "copy": "State uncertainty explicitly for this current analysis, recommendation, or draft.\n\nRequirements:\n\n- distinguish assumptions from unknowns\n- express confidence in plain language\n- name the single update that would most change the answer\n\nReturn:\n\n- assumptions\n- unknowns\n- confidence level\n- what would most change the conclusion\n\nInput:\n{paste current analysis, recommendation, or draft}",
      "body": [
        [
          "Best use",
          "after exploration, before decisions, during critique, during reflection"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "prompts/blocks/guardrail.uncertainty/prompt.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Prompt Block",
      "key": "core.guardrail.disconfirming-evidence",
      "aliases": [
        "core.guardrail-disconfirming-evidence"
      ],
      "title": "Disconfirming Evidence Guardrail",
      "summary": "Use this prompt block when you may be talking yourself into a preferred answer.",
      "tags": [
        "disconfirming",
        "evidence",
        "guardrail"
      ],
      "copy": "Force a check against disconfirming evidence for this current conclusion, recommendation, or preferred option.\n\nRequirements:\n\n- prioritize the strongest real opposing case\n- do not manufacture weak objections\n- update the conclusion if the opposing evidence materially changes it\n\nReturn:\n\n- current conclusion\n- strongest opposing evidence or argument\n- what would be true if the conclusion were wrong\n- whether the conclusion still stands and why\n\nInput:\n{paste current conclusion, recommendation, or preferred option}",
      "body": [
        [
          "Best use",
          "before a high-stakes decision, after a persuasive draft or recommendation, when the current conclusion feels too smooth"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "prompts/blocks/guardrail.disconfirming-evidence/prompt.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Prompt Block",
      "key": "core.assumption.audit",
      "aliases": [
        "core.assumption-audit"
      ],
      "title": "Assumption Audit",
      "summary": "Use this prompt block when a task depends on important assumptions.",
      "tags": [
        "assumption",
        "audit"
      ],
      "copy": "Enumerate all significant assumptions behind this plan, decision, argument, or recommendation.\n\nRequirements:\n\n- focus first on assumptions where being wrong would most damage the outcome\n- separate empirical claims from causal bets and value judgments\n- do not invent evidence that is not present\n\nReturn for each:\n\n- assumption\n- type (empirical / causal / value)\n- confidence (high / medium / low)\n- what would falsify it\n\nInput:\n{paste plan, decision, argument, or recommendation}",
      "body": [
        [
          "Best use",
          "before committing to a plan or decision, before a critique that needs its premises checked, when uncertainty feels hidden"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "prompts/blocks/assumption.audit/prompt.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Prompt Block",
      "key": "core.scope.frame",
      "aliases": [
        "core.scope-frame"
      ],
      "title": "Scope Frame",
      "summary": "Use this prompt block when a task needs explicit boundaries.",
      "tags": [
        "scope",
        "frame"
      ],
      "copy": "Define the scope of this task or project explicitly.\n\nRequirements:\n\n- distinguish boundaries from preferences\n- name the one boundary that matters most\n- explain what is being excluded if that exclusion prevents drift\n\nReturn:\n\n- what is in scope\n- what is out of scope\n- most important boundary to hold\n- what has been deliberately excluded and why\n\nInput:\n{paste task, project, or request}",
      "body": [
        [
          "Best use",
          "when a task is sprawling or underspecified, before work begins, when scope drift is a risk"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "prompts/blocks/scope.frame/prompt.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Prompt Block",
      "key": "core.schema.decision-memo",
      "aliases": [
        "core.schema-decision-memo"
      ],
      "title": "Decision Memo Schema",
      "summary": "Use this prompt block to standardize how decisions are captured.",
      "tags": [
        "decision",
        "memo"
      ],
      "copy": "Render this chosen direction or decision as a structured memo.\n\nRequirements:\n\n- make the actual choice explicit\n- keep rationale concise and decision-relevant\n- include only the risks and tradeoffs that matter to execution\n\nReturn:\n\n- decision\n- rationale\n- tradeoffs\n- risks\n- confidence\n- next action\n\nInput:\n{paste chosen option or decision context}",
      "body": [
        [
          "Best use",
          "after choosing, before execution planning, when you want later reflection to be easier"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "prompts/blocks/schema.decision-memo/prompt.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Prompt Block",
      "key": "core.schema.execution-brief",
      "aliases": [
        "core.schema-execution-brief"
      ],
      "title": "Execution Brief Schema",
      "summary": "Use this prompt block to standardize how a chosen direction turns into action.",
      "tags": [
        "execution",
        "brief"
      ],
      "copy": "Render this chosen direction, plan, or handoff as a structured execution brief.\n\nRequirements:\n\n- make ownership and sequencing explicit\n- name dependencies before milestones drift\n- keep the first checkpoint close enough to catch early failure\n\nReturn:\n\n- objective\n- owner or responsible role\n- milestones\n- dependencies\n- major risks\n- first checkpoint\n- immediate next action\n\nInput:\n{paste chosen direction, plan, or handoff context}",
      "body": [
        [
          "Best use",
          "after a decision, before handoff or delegation, when execution details are starting to drift"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "prompts/blocks/schema.execution-brief/prompt.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.generate-options",
      "aliases": [
        "snippet.generate-options"
      ],
      "title": "Generate Options",
      "summary": "Use when you need multiple directions before choosing.",
      "tags": [
        "generate",
        "options"
      ],
      "copy": "Generate a diverse set of plausible options.\n\nRequirements:\n- include genuinely different approaches, not small variations\n- include at least one option that contradicts the default instinct\n- note what each option optimizes for\n- note the main downside of each option\n- surface any obvious unknowns\n- name the comparison dimension that matters most next\n\nReturn:\n- option\n- what it optimizes for\n- downside\n- unknowns\n- next comparison angle\n\nProblem:\n{paste problem}\n\nConstraints, limits, or non-goals:\n{paste constraints, limits, or non-goals}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/generate-options.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.brainstorm-angles",
      "aliases": [
        "snippet.brainstorm-angles"
      ],
      "title": "Brainstorm Angles",
      "summary": "Use when you want fresh perspectives rather than polished ideas.",
      "tags": [
        "brainstorm",
        "angles"
      ],
      "copy": "Brainstorm unexpected but plausible angles on this.\n\nRequirements:\n- avoid obvious first-pass ideas\n- include at least one contrarian angle\n- include at least one practical angle\n- include at least one high-upside angle\n\nTopic:\n{paste topic}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/brainstorm-angles.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.clarify-task",
      "aliases": [
        "snippet.clarify-task"
      ],
      "title": "Clarify Task",
      "summary": "Use when a request is vague or overloaded.",
      "tags": [
        "clarify",
        "task"
      ],
      "copy": "Clarify this task before trying to solve it.\n\nReturn:\n- what the task most likely means\n- the biggest missing details\n- the best clarifying questions to ask next\n- a cleaner version of the task if I want to hand it back\n- the best next reasoning step\n\nTask:\n{paste task}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/clarify-task.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.compare-options",
      "aliases": [
        "snippet.compare-options"
      ],
      "title": "Compare Options",
      "summary": "Use when you already have options and need a structured comparison.",
      "tags": [
        "compare",
        "options"
      ],
      "copy": "Compare these options in a compact decision table.\n\nReturn columns:\n- option\n- criteria fit\n- strengths\n- weaknesses\n- best use case\n- key risk\n- overall judgment\n\nContext:\n{paste context}\n\nCriteria:\n{paste criteria}\n\nOptions:\n{paste options}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/compare-options.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.choose-under-uncertainty",
      "aliases": [
        "snippet.choose-under-uncertainty"
      ],
      "title": "Choose Under Uncertainty",
      "summary": "Use when you need a best current choice, not a perfect answer.",
      "tags": [
        "choose",
        "under",
        "uncertainty"
      ],
      "copy": "Choose the best current option under uncertainty.\n\nRequirements:\n- state the criteria being used\n- choose one option or explicitly say no decision yet\n- name the biggest uncertainty\n- name what evidence would most change the decision\n- give the next action\n\nContext:\n{paste context}\n\nOptions:\n{paste options}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/choose-under-uncertainty.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.explore-exploit-decision",
      "aliases": [
        "snippet.explore-exploit-decision"
      ],
      "title": "Explore / Exploit Decision",
      "summary": "Use when you need to decide whether to keep searching, learning, or generating options versus committing to the best current path.",
      "tags": [
        "explore",
        "exploit",
        "decision"
      ],
      "copy": "Decide whether this situation calls for more exploration or for exploitation of the best current option.\n\nReturn:\n- current decision context\n- best current option\n- reasons to keep exploring\n- reasons to exploit now\n- value of additional information\n- cost of delay\n- reversibility of the decision\n- decision: explore more / exploit now / exploit with a bounded test\n- trigger that would flip the decision\n- next action\n\nRequirements:\n- prefer exploitation when the best current option is already strong and further search has low expected value\n- prefer exploration when uncertainty is still highly decision-relevant and cheap learning is available\n- if the answer is mixed, recommend a bounded exploration window or cheap test rather than open-ended searching\n\nContext:\n{paste context}\n\nCurrent options or path:\n{paste options or current path}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/explore-exploit-decision.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.prioritize-opportunities",
      "aliases": [
        "snippet.prioritize-opportunities"
      ],
      "title": "Prioritize Opportunities",
      "summary": "Use when you have too many plausible projects, bets, or tasks competing for attention.",
      "tags": [
        "prioritize",
        "opportunities"
      ],
      "copy": "Prioritize these opportunities or tasks.\n\nReturn columns:\n- item\n- expected upside\n- strategic fit\n- effort or cost\n- urgency or timing\n- reversibility\n- key risk\n- recommendation (do now / later / drop)\n\nRequirements:\n- explain the top two picks\n- identify one attractive option that should still wait\n- avoid ranking purely by excitement\n\nContext:\n{paste context}\n\nItems:\n{paste items}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/prioritize-opportunities.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.design-cheap-test",
      "aliases": [
        "snippet.design-cheap-test"
      ],
      "title": "Design Cheap Test",
      "summary": "Use when uncertainty is blocking commitment and you need the smallest useful experiment.",
      "tags": [
        "design",
        "cheap",
        "test"
      ],
      "copy": "Design the cheapest useful test for this idea, decision, or plan.\n\nReturn:\n- what decision or assumption needs de-risking\n- the riskiest unknown\n- the cheapest credible test\n- success signal\n- failure signal\n- time or cost ceiling\n- what to do if the signal is positive\n- what to do if the signal is negative\n\nContext:\n{paste context}\n\nResource ceiling, if any:\n{paste time, budget, or effort limit}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/design-cheap-test.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.decision-journal-entry",
      "aliases": [
        "snippet.decision-journal-entry"
      ],
      "title": "Decision Journal Entry",
      "summary": "Use when you want to record a decision well enough to reflect on it later.",
      "tags": [
        "decision",
        "journal",
        "entry"
      ],
      "copy": "Turn this into a decision journal entry.\n\nReturn:\n- decision\n- options considered\n- criteria used\n- key assumptions\n- confidence level\n- what would prove this wrong\n- next checkpoint date\n\nDecision context:\n{paste context}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/decision-journal-entry.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.plan-next-actions",
      "aliases": [
        "snippet.plan-next-actions"
      ],
      "title": "Plan Next Actions",
      "summary": "Use when you have a chosen direction and need an executable plan.",
      "tags": [
        "plan",
        "next",
        "actions"
      ],
      "copy": "Turn this into a practical next-step plan.\n\nReturn:\n- goal\n- ordered steps\n- dependencies\n- likely blockers\n- first checkpoint\n- first concrete action\n- what to check after step one\n\nContext:\n{paste context}\n\nDeadline, constraint, or time horizon:\n{paste deadline, constraint, or time horizon}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/plan-next-actions.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.stress-test-assumptions",
      "aliases": [
        "snippet.stress-test-assumptions"
      ],
      "title": "Stress Test Assumptions",
      "summary": "Use when a plan or decision rests on assumptions that have not been pressure-tested.",
      "tags": [
        "stress",
        "test",
        "assumptions"
      ],
      "copy": "Stress test the assumptions behind this.\n\nFor each significant assumption:\n- state the assumption\n- rate confidence (high / medium / low)\n- name the failure mode if the assumption is wrong\n- suggest the cheapest way to verify it before committing\n\nFocus first on assumptions where being wrong would most damage the outcome.\n\nInput:\n{paste plan, decision, or argument}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/stress-test-assumptions.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.write-first-draft",
      "aliases": [
        "snippet.write-first-draft"
      ],
      "title": "Write First Draft",
      "summary": "Use when you want a working draft quickly.",
      "tags": [
        "write",
        "first",
        "draft"
      ],
      "copy": "Write a strong first draft.\n\nRequirements:\n- optimize for clarity over polish\n- avoid filler and generic throat-clearing\n- make the structure easy to revise later\n\nAudience:\n{paste audience}\n\nGoal:\n{paste goal}\n\nKey points:\n{paste points}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/write-first-draft.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.rewrite-for-clarity",
      "aliases": [
        "snippet.rewrite-for-clarity"
      ],
      "title": "Rewrite For Clarity",
      "summary": "Use when a draft is muddled, bloated, or indirect.",
      "tags": [
        "rewrite",
        "clarity"
      ],
      "copy": "Rewrite this for clarity.\n\nRequirements:\n- keep the meaning\n- remove redundancy\n- tighten structure\n- make the key point obvious earlier\n- preserve useful nuance\n\nText:\n{paste draft}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/rewrite-for-clarity.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.critique-argument",
      "aliases": [
        "snippet.critique-argument"
      ],
      "title": "Critique Argument",
      "summary": "Use when you want the weaknesses in a claim, draft, or argument.",
      "tags": [
        "critique",
        "argument"
      ],
      "copy": "Critique this argument.\n\nFocus on:\n- hidden assumptions\n- weak evidence\n- logical gaps\n- overclaims\n- what a smart skeptic would attack first\n\nReturn:\n- strongest part\n- weakest part\n- top three findings\n- what would strengthen it most\n\nArgument:\n{paste argument}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/critique-argument.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.position-draft",
      "aliases": [
        "snippet.position-draft"
      ],
      "title": "Position Draft",
      "summary": "Use when you need to argue a clear position with evidence and honest counter-acknowledgment.",
      "tags": [
        "position",
        "draft"
      ],
      "copy": "Write a clear position on this topic.\n\nReturn:\n- the position stated in one sentence\n- two or three strongest supporting reasons with evidence\n- the strongest objection to this position\n- a direct response to that objection\n- what evidence would change this position\n\nTopic or question:\n{paste topic}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/position-draft.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.summarize-source",
      "aliases": [
        "snippet.summarize-source"
      ],
      "title": "Summarize Source",
      "summary": "Use when you need a dense source turned into something useful.",
      "tags": [
        "summarize",
        "source"
      ],
      "copy": "Summarize this source for practical use.\n\nReturn:\n- core thesis\n- most important supporting points\n- useful facts or evidence\n- caveats or limitations\n- what matters for my purpose\n\nMy purpose:\n{paste purpose}\n\nSource:\n{paste source}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/summarize-source.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.extract-insights",
      "aliases": [
        "snippet.extract-insights"
      ],
      "title": "Extract Insights",
      "summary": "Use when notes, transcripts, or documents contain signal buried in noise.",
      "tags": [
        "extract",
        "insights"
      ],
      "copy": "Extract the highest-value insights from this material.\n\nReturn:\n- key insight\n- why it matters\n- supporting evidence\n- possible action or implication\n\nMy purpose:\n{paste purpose or decision this should inform}\n\nMaterial:\n{paste material}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/extract-insights.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.cause-mapping",
      "aliases": [
        "snippet.cause-mapping"
      ],
      "title": "Cause Mapping",
      "summary": "Use when you need to understand why an outcome happened, not just what happened.",
      "tags": [
        "cause",
        "mapping"
      ],
      "copy": "Map the causes behind this outcome or problem.\n\nRequirements:\n- start with the visible symptom\n- trace back at least three levels of causation\n- identify where the causal chain branches\n- mark the earliest point where intervention was plausible\n- name the most likely root cause\n\nProblem or outcome:\n{paste problem or outcome}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/cause-mapping.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.blind-spot-check",
      "aliases": [
        "snippet.blind-spot-check"
      ],
      "title": "Blind Spot Check",
      "summary": "Use when you want to surface what you are probably not thinking about.",
      "tags": [
        "blind",
        "spot"
      ],
      "copy": "Surface the blind spots I am probably missing here.\n\nLook for:\n- perspectives of stakeholders I may be underweighting\n- common failure categories that apply to this type of problem\n- hidden incentives or dynamics I may be ignoring\n- the question I should be asking but am not\n- evidence I might be filtering out because it is inconvenient\n\nContext:\n{paste context}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/blind-spot-check.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.research-questions",
      "aliases": [
        "snippet.research-questions"
      ],
      "title": "Research Questions",
      "summary": "Use when you need to map what to investigate next.",
      "tags": [
        "research",
        "questions"
      ],
      "copy": "Generate the best research questions for this topic.\n\nRequirements:\n- prioritize questions that would materially improve understanding\n- separate foundational questions from edge-case questions\n- note which questions are most decision-relevant\n- note what would change if each important question were answered\n\nMy purpose:\n{paste the decision, project, or output this research supports}\n\nTopic:\n{paste topic}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/research-questions.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.stakeholder-map",
      "aliases": [
        "snippet.stakeholder-map"
      ],
      "title": "Stakeholder Map",
      "summary": "Use when buy-in, resistance, or coordination will shape the outcome.",
      "tags": [
        "stakeholder",
        "map"
      ],
      "copy": "Map the stakeholders in this situation.\n\nReturn for each stakeholder:\n- stakeholder\n- goals\n- likely concerns\n- influence level\n- current support level\n- what they need to say yes\n- best communication move\n\nThen return:\n- biggest alignment risk\n- the single most important conversation to have next\n\nDecision, project, or goal:\n{paste the outcome you are trying to achieve}\n\nSituation:\n{paste situation}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/stakeholder-map.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.meeting-prep",
      "aliases": [
        "snippet.meeting-prep"
      ],
      "title": "Meeting Prep",
      "summary": "Use when you need to prepare for a conversation efficiently.",
      "tags": [
        "meeting",
        "prep"
      ],
      "copy": "Prepare me for this meeting.\n\nReturn:\n- likely goals\n- what I need to know\n- smart questions to ask\n- likely risks or tensions\n- best outcome\n- minimum acceptable outcome\n\nMy desired outcome:\n{paste what I want from the meeting}\n\nContext:\n{paste meeting context}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/meeting-prep.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.debug-confusion",
      "aliases": [
        "snippet.debug-confusion"
      ],
      "title": "Debug Confusion",
      "summary": "Use when you feel stuck but do not know why.",
      "tags": [
        "debug",
        "confusion"
      ],
      "copy": "Help me debug my confusion.\n\nReturn:\n- what I may be conflating\n- what assumptions might be wrong\n- what is still underspecified\n- what the real question might be\n- the smallest next step to reduce confusion\n\nSituation:\n{paste situation}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/debug-confusion.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.weekly-review",
      "aliases": [
        "snippet.weekly-review"
      ],
      "title": "Weekly Review",
      "summary": "Use when reflecting on a week of work or decisions.",
      "tags": [
        "weekly",
        "review"
      ],
      "copy": "Run a useful weekly review.\n\nReturn:\n- what moved forward\n- what stalled\n- what created the most value\n- what created friction\n- what I should stop doing\n- what I should repeat next week\n- the single best focus for next week\n\nNotes:\n{paste notes}",
      "body": [],
      "family": "",
      "group": "",
      "sourcePath": "prompts/snippets/weekly-review.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.prompt-critique",
      "aliases": [
        "snippet.prompt-critique"
      ],
      "title": "Prompt Critique",
      "summary": "Use when a prompt feels vague, bloated, or unreliable.",
      "tags": [
        "critique",
        "repair"
      ],
      "copy": "Critique this prompt for reliability and clarity.\n\nFocus on:\n- unclear goals\n- missing constraints\n- weak or ambiguous output format\n- failure modes\n- unnecessary verbosity\n- places where the model could reasonably misread intent\n\nReturn:\n- what the prompt is trying to do\n- the biggest weaknesses\n- the highest-leverage fixes\n- a revised prompt skeleton\n\nDesired task or output:\n{paste the job this prompt should do}\n\nObserved failure modes, if any:\n{paste what is going wrong, if known}\n\nPrompt:\n{paste prompt}",
      "body": [],
      "family": "Prompt Repair",
      "group": "",
      "sourcePath": "prompts/snippets/prompt-critique.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.prompt-rewrite",
      "aliases": [
        "snippet.prompt-rewrite"
      ],
      "title": "Prompt Rewrite",
      "summary": "Use when you want to turn a rough prompt into a sharper version quickly.",
      "tags": [
        "rewrite",
        "repair"
      ],
      "copy": "Rewrite this prompt for better model performance.\n\nRequirements:\n- preserve the original intent\n- make the desired output explicit\n- remove ambiguity and redundancy\n- add only the minimum useful constraints\n- keep it short unless detail clearly improves results\n\nReturn:\n- revised prompt\n- short note on what changed and why\n\nDesired task or output:\n{paste the job this prompt should do}\n\nObserved failure modes, if any:\n{paste what is going wrong, if known}\n\nPrompt:\n{paste prompt}",
      "body": [],
      "family": "Prompt Repair",
      "group": "",
      "sourcePath": "prompts/snippets/prompt-rewrite.md"
    },
    {
      "section": "Block",
      "blockType": "core",
      "sourceKind": "Snippet",
      "key": "core.prompt-compare",
      "aliases": [
        "snippet.prompt-compare"
      ],
      "title": "Prompt Compare",
      "summary": "Use when you have two or more prompt variants and want to choose the strongest one.",
      "tags": [
        "compare",
        "repair"
      ],
      "copy": "Compare these prompt variants and recommend the best one.\n\nJudge them on:\n- clarity\n- specificity\n- likelihood of producing the requested output\n- token efficiency\n- risk of model confusion\n\nReturn:\n- best prompt\n- why it is strongest\n- what to borrow from the others\n- one or two targeted edits to make it even better\n\nDesired task or output:\n{paste the job these prompts should do}\n\nVariants:\n{paste prompt variants}",
      "body": [],
      "family": "Prompt Repair",
      "group": "",
      "sourcePath": "prompts/snippets/prompt-compare.md"
    },
    {
      "section": "Block",
      "blockType": "lens",
      "sourceKind": "Lens",
      "key": "lens.coordination-plan",
      "aliases": [
        "lens.game-theory-coordination-plan"
      ],
      "title": "Coordination Plan",
      "summary": "Use when the main problem is getting multiple actors to align without drift.",
      "tags": [
        "coordination",
        "plan",
        "game",
        "theory"
      ],
      "copy": "Analyze this as a coordination problem.\n\nReturn:\n- what must be coordinated\n- likely focal points\n- sources of misalignment\n- commitments needed\n- communication or protocol changes\n- how to detect drift early\n\nSituation:\n{paste situation}",
      "body": [],
      "family": "",
      "group": "Game Theory",
      "sourcePath": "prompts/concepts/game-theory/coordination-plan.md"
    },
    {
      "section": "Block",
      "blockType": "lens",
      "sourceKind": "Lens",
      "key": "lens.incentive-audit",
      "aliases": [
        "lens.game-theory-incentive-audit"
      ],
      "title": "Incentive Audit",
      "summary": "Use when behavior is being shaped by rewards, costs, or perverse incentives.",
      "tags": [
        "incentive",
        "audit",
        "game",
        "theory"
      ],
      "copy": "Analyze this situation as an incentive system.\n\nReturn:\n- actors\n- goals\n- explicit incentives\n- hidden incentives\n- likely equilibrium behavior\n- perverse incentives\n- one lever to realign behavior without creating new gaming\n\nSituation:\n{paste situation}",
      "body": [],
      "family": "",
      "group": "Game Theory",
      "sourcePath": "prompts/concepts/game-theory/incentive-audit.md"
    },
    {
      "section": "Block",
      "blockType": "lens",
      "sourceKind": "Lens",
      "key": "lens.signaling-check",
      "aliases": [
        "lens.game-theory-signaling-check"
      ],
      "title": "Signaling Check",
      "summary": "Use when words, status, or actions may be sending a signal to other people.",
      "tags": [
        "signaling",
        "game",
        "theory"
      ],
      "copy": "Analyze the signals in this situation.\n\nReturn:\n- which signals are credible vs cheap talk\n- who is sending each signal\n- who the audience is\n- what action would be a stronger signal than words\n- where noise or ambiguity could mislead\n\nSituation:\n{paste situation}",
      "body": [],
      "family": "",
      "group": "Game Theory",
      "sourcePath": "prompts/concepts/game-theory/signaling-check.md"
    },
    {
      "section": "Block",
      "blockType": "lens",
      "sourceKind": "Lens",
      "key": "lens.behavior-change-plan",
      "aliases": [
        "lens.psychology-behavior-change-plan"
      ],
      "title": "Behavior Change Plan",
      "summary": "Use when an intention needs to become a repeatable habit.",
      "tags": [
        "behavior",
        "change",
        "plan",
        "psychology"
      ],
      "copy": "Turn this intention into a behavior-change plan.\n\nReturn:\n- target behavior\n- cue\n- friction reduction\n- implementation intention\n- environment change\n- feedback loop\n- likely failure mode\n- minimum viable habit\n\nIntention:\n{paste intention}",
      "body": [],
      "family": "",
      "group": "Psychology",
      "sourcePath": "prompts/concepts/psychology/behavior-change-plan.md"
    },
    {
      "section": "Block",
      "blockType": "lens",
      "sourceKind": "Lens",
      "key": "lens.bias-check",
      "aliases": [
        "lens.psychology-bias-check"
      ],
      "title": "Bias Check",
      "summary": "Use when judgment may be distorted by a known cognitive bias.",
      "tags": [
        "bias",
        "psychology"
      ],
      "copy": "Review this through a cognitive-bias lens.\n\nReturn:\n- likely biases at play\n- how each bias would distort judgment\n- the most useful counter-question for each bias\n- what evidence would reduce the distortion\n- what a calmer outside observer would probably say\n\nSituation:\n{paste situation}",
      "body": [],
      "family": "",
      "group": "Psychology",
      "sourcePath": "prompts/concepts/psychology/bias-check.md"
    },
    {
      "section": "Block",
      "blockType": "lens",
      "sourceKind": "Lens",
      "key": "lens.motivation-diagnosis",
      "aliases": [
        "lens.psychology-motivation-diagnosis"
      ],
      "title": "Motivation Diagnosis",
      "summary": "Use when behavior is stuck and you need to know why.",
      "tags": [
        "motivation",
        "diagnosis",
        "psychology"
      ],
      "copy": "Diagnose why this behavior is or is not happening.\n\nReturn:\n- goal clarity\n- ability / skill gap\n- friction / effort\n- reward / feedback loop\n- identity / values conflict\n- social pressure\n- emotional resistance\n- smallest intervention\n\nSituation:\n{paste situation}",
      "body": [],
      "family": "",
      "group": "Psychology",
      "sourcePath": "prompts/concepts/psychology/motivation-diagnosis.md"
    },
    {
      "section": "Block",
      "blockType": "lens",
      "sourceKind": "Lens",
      "key": "lens.complexity-tradeoff",
      "aliases": [
        "lens.computer-science-complexity-tradeoff"
      ],
      "title": "Complexity Tradeoff",
      "summary": "Use when you need to choose an approach based on cost, scale, or maintainability.",
      "tags": [
        "complexity",
        "tradeoff",
        "computer",
        "science"
      ],
      "copy": "Evaluate the algorithm or system tradeoffs.\n\nReturn:\n- time complexity\n- space complexity\n- latency or throughput impact\n- bottlenecks\n- maintainability cost\n- simplest adequate approach\n\nContext:\n{paste context}",
      "body": [],
      "family": "",
      "group": "Computer Science",
      "sourcePath": "prompts/concepts/computer-science/complexity-tradeoff.md"
    },
    {
      "section": "Block",
      "blockType": "lens",
      "sourceKind": "Lens",
      "key": "lens.debugger-loop",
      "aliases": [
        "lens.computer-science-debugger-loop"
      ],
      "title": "Debugger Loop",
      "summary": "Use when you need a systematic way to localize a bug or failure.",
      "tags": [
        "debugger",
        "loop",
        "computer",
        "science"
      ],
      "copy": "Debug this systematically.\n\nReturn:\n- reproduction steps\n- observations\n- hypotheses\n- experiments\n- localization\n- fix\n- regression test\n\nBug or failure:\n{paste bug or failure}",
      "body": [],
      "family": "",
      "group": "Computer Science",
      "sourcePath": "prompts/concepts/computer-science/debugger-loop.md"
    },
    {
      "section": "Block",
      "blockType": "lens",
      "sourceKind": "Lens",
      "key": "lens.interface-contract-review",
      "aliases": [
        "lens.computer-science-interface-contract-review"
      ],
      "title": "Interface Contract Review",
      "summary": "Use when failures may be happening at a boundary between components.",
      "tags": [
        "interface",
        "contract",
        "review",
        "computer",
        "science"
      ],
      "copy": "Review the interface boundary.\n\nReturn:\n- inputs\n- outputs\n- contracts\n- error handling\n- retry and idempotency assumptions\n- observability\n- one boundary-hardening change\n\nBoundary:\n{paste boundary}",
      "body": [],
      "family": "",
      "group": "Computer Science",
      "sourcePath": "prompts/concepts/computer-science/interface-contract-review.md"
    },
    {
      "section": "Block",
      "blockType": "lens",
      "sourceKind": "Lens",
      "key": "lens.invariant-check",
      "aliases": [
        "lens.computer-science-invariant-check"
      ],
      "title": "Invariant Check",
      "summary": "Use when correctness depends on things staying true across steps.",
      "tags": [
        "invariant",
        "computer",
        "science"
      ],
      "copy": "Find the invariants in this system or argument.\n\nReturn:\n- invariants\n- preconditions\n- postconditions\n- edge cases\n- failure modes\n- a test that would catch violations\n\nSystem or argument:\n{paste system or argument}",
      "body": [],
      "family": "",
      "group": "Computer Science",
      "sourcePath": "prompts/concepts/computer-science/invariant-check.md"
    },
    {
      "section": "Block",
      "blockType": "rubric",
      "sourceKind": "Rubric",
      "key": "rubric.decision-quality",
      "aliases": [],
      "title": "Decision Quality",
      "summary": "Use this checklist after a decision draft.",
      "tags": [
        "decision",
        "quality"
      ],
      "copy": "",
      "body": [
        [
          "Questions",
          "Is the actual choice explicit?, Are the criteria visible?, Are tradeoffs named rather than hidden?, Is uncertainty acknowledged?, Is there a concrete next action?, Would future-you understand why this decision was made?"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "rubrics/decision-quality.md"
    },
    {
      "section": "Block",
      "blockType": "rubric",
      "sourceKind": "Rubric",
      "key": "rubric.argument-quality",
      "aliases": [],
      "title": "Argument Quality",
      "summary": "Use this checklist after drafting or critiquing an argument.",
      "tags": [
        "argument",
        "quality"
      ],
      "copy": "",
      "body": [
        [
          "Questions",
          "Is the core claim stated in one sentence?, Is the evidence proportionate to the strength of the claim?, Are the key premises visible?, Is the strongest objection acknowledged and addressed?, Does the conclusion actually follow from the argument?, Is anything being asserted that should be proven?"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "rubrics/argument-quality.md"
    },
    {
      "section": "Block",
      "blockType": "rubric",
      "sourceKind": "Rubric",
      "key": "rubric.plan-quality",
      "aliases": [],
      "title": "Plan Quality",
      "summary": "Use this checklist after a plan.",
      "tags": [
        "plan",
        "quality"
      ],
      "copy": "",
      "body": [
        [
          "Questions",
          "Are the steps ordered clearly?, Are dependencies visible?, Are likely blockers named?, Is the first action concrete enough to do now?, Does the plan avoid unnecessary complexity?, Is there a check point after early execution?"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "rubrics/plan-quality.md"
    },
    {
      "section": "Block",
      "blockType": "rubric",
      "sourceKind": "Rubric",
      "key": "rubric.writing-quality",
      "aliases": [],
      "title": "Writing Quality",
      "summary": "Use this checklist after drafting or rewriting.",
      "tags": [
        "writing",
        "quality"
      ],
      "copy": "",
      "body": [
        [
          "Questions",
          "Is the main point clear early?, Is anything redundant?, Are claims stronger than the evidence supports?, Is the structure easy to follow?, Does each paragraph earn its place?, Is the next action or takeaway obvious?"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "rubrics/writing-quality.md"
    },
    {
      "section": "Block",
      "blockType": "rubric",
      "sourceKind": "Rubric",
      "key": "rubric.reflection-quality",
      "aliases": [],
      "title": "Reflection Quality",
      "summary": "Use this checklist after a review or retrospective.",
      "tags": [
        "reflection",
        "quality"
      ],
      "copy": "",
      "body": [
        [
          "Questions",
          "Did this go beyond recap?, Is there at least one reusable lesson?, Is there at least one concrete change to make?, Did it identify what actually caused the outcome?, Did it avoid blame theater?, Will this make a future decision or workflow better?"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "rubrics/reflection-quality.md"
    },
    {
      "section": "Block",
      "blockType": "rubric",
      "sourceKind": "Rubric",
      "key": "rubric.prompt-quality",
      "aliases": [],
      "title": "Prompt Quality",
      "summary": "Use this checklist after drafting or revising a prompt.",
      "tags": [
        "quality"
      ],
      "copy": "",
      "body": [
        [
          "Questions",
          "Is the task specific?, Is the output shape explicit?, Are constraints and non-goals visible?, Is the model likely to misread the request?, Is there enough context to solve it without guessing?, Would a cleaner version of this prompt be easier to use?"
        ]
      ],
      "family": "",
      "group": "",
      "sourcePath": "rubrics/prompt-quality.md"
    }
  ],
  "stacks": [
    {
      "section": "Stack",
      "key": "stack.problem-framing",
      "title": "Problem Framing",
      "summary": "Use when the task is vague and you need a clean starting point.",
      "tags": [
        "problem",
        "framing"
      ],
      "body": [
        [
          "Useful inputs",
          "the raw request, problem statement, or situation, any visible constraints or deadlines, any facts you already know versus what still feels unclear"
        ],
        [
          "Suggested blocks",
          "`mode.explore` -> `core.frame.task` -> `strategy.problem_split` -> `core.scope.frame` -> `core.guardrail.uncertainty`"
        ],
        [
          "Expected outcome",
          "clear problem frame, subproblems, open questions, best next step"
        ]
      ],
      "sourcePath": "stacks/problem-framing.md"
    },
    {
      "section": "Stack",
      "key": "stack.explore-to-decision",
      "title": "Explore To Decision",
      "summary": "Use when you need options first and a choice second.",
      "tags": [
        "explore",
        "decision"
      ],
      "body": [
        [
          "Useful inputs",
          "the decision context or problem to solve, any candidate options already on the table, any known criteria, constraints, or deadline"
        ],
        [
          "Suggested blocks",
          "`mode.explore` -> `core.generate-options` -> `core.brainstorm-angles` -> `core.frame.success-criteria` -> `mode.decide` -> `core.compare-options` -> `core.choose-under-uncertainty` -> `core.schema.decision-memo`"
        ],
        [
          "Expected outcome",
          "option set, explicit criteria, comparison, chosen direction, rationale, next action"
        ]
      ],
      "sourcePath": "stacks/explore-to-decision.md"
    },
    {
      "section": "Stack",
      "key": "stack.explore-vs-exploit",
      "title": "Explore Vs Exploit",
      "summary": "Use when you are unsure whether to keep searching or to commit to the best current option.",
      "tags": [
        "explore",
        "exploit"
      ],
      "body": [
        [
          "Useful inputs",
          "the current path or best known option, alternative options or search space, if any, the cost of delay, reversibility, or learning opportunity"
        ],
        [
          "Suggested blocks",
          "`mode.decide` -> `core.frame.success-criteria` -> `core.explore-exploit-decision` -> `core.guardrail.uncertainty` -> `core.schema.execution-brief`"
        ],
        [
          "Expected outcome",
          "clear recommendation to explore, exploit, or run a bounded test, explicit rationale, trigger that would change the call, immediate next action"
        ]
      ],
      "sourcePath": "stacks/explore-vs-exploit.md"
    },
    {
      "section": "Stack",
      "key": "stack.prioritize-portfolio",
      "title": "Prioritize Portfolio",
      "summary": "Use when several plausible bets compete for limited time, money, or attention.",
      "tags": [
        "prioritize",
        "portfolio"
      ],
      "body": [
        [
          "Useful inputs",
          "the list of candidate bets, projects, or tasks, resource constraints such as time, budget, or attention, any explicit success criteria or strategic priorities"
        ],
        [
          "Suggested blocks",
          "`mode.decide` -> `core.frame.success-criteria` -> `core.prioritize-opportunities` -> `core.schema.execution-brief` -> `core.guardrail.uncertainty`"
        ],
        [
          "Expected outcome",
          "ranked bets, now versus later cuts, execution brief for the top priority, visible uncertainty"
        ]
      ],
      "sourcePath": "stacks/prioritize-portfolio.md"
    },
    {
      "section": "Stack",
      "key": "stack.de-risk-with-test",
      "title": "De-Risk With Test",
      "summary": "Use when uncertainty is too high for full commitment but low enough to test.",
      "tags": [
        "risk",
        "test"
      ],
      "body": [
        [
          "Useful inputs",
          "the current idea, plan, or decision under consideration, the main uncertainty blocking commitment, any real budget, time, or effort ceiling for a test"
        ],
        [
          "Suggested blocks",
          "`mode.decide` -> `core.frame.success-criteria` -> `core.design-cheap-test` -> `core.schema.execution-brief` -> `core.guardrail.uncertainty`"
        ],
        [
          "Expected outcome",
          "core uncertainty, cheapest credible test, success and failure signals, next action with checkpoint"
        ]
      ],
      "sourcePath": "stacks/de-risk-with-test.md"
    },
    {
      "section": "Stack",
      "key": "stack.pressure-test-plan",
      "title": "Pressure Test Plan",
      "summary": "Use when you have a plan and want to stress it before committing.",
      "tags": [
        "pressure",
        "test",
        "plan"
      ],
      "body": [
        [
          "Useful inputs",
          "the current plan, recommendation, or proposal, the intended outcome and constraints, any assumptions that already feel shaky"
        ],
        [
          "Suggested blocks",
          "`mode.critique` -> `strategy.premortem` -> `strategy.red_team` -> `core.assumption.audit` -> `core.stress-test-assumptions`"
        ],
        [
          "Expected outcome",
          "prioritized risks, exposed assumptions, hardest-to-dismiss objections, concrete mitigations"
        ]
      ],
      "sourcePath": "stacks/pressure-test-plan.md"
    },
    {
      "section": "Stack",
      "key": "stack.debug-a-failure",
      "title": "Debug A Failure",
      "summary": "Use when a bug, incident, or broken workflow needs a structured diagnosis instead of random guessing.",
      "tags": [
        "debug",
        "failure"
      ],
      "body": [
        [
          "Useful inputs",
          "expected behavior versus actual behavior, reproduction steps, logs, or error evidence, the system boundary or component most likely involved"
        ],
        [
          "Suggested blocks",
          "`mode.critique` -> `lens.debugger-loop` -> `lens.interface-contract-review` -> `lens.invariant-check` -> `core.plan-next-actions`"
        ],
        [
          "Expected outcome",
          "a tighter failure hypothesis, the highest-value next experiment, likely boundary or invariant break, a practical next-step plan"
        ]
      ],
      "sourcePath": "stacks/debug-a-failure.md"
    },
    {
      "section": "Stack",
      "key": "stack.source-to-brief",
      "title": "Source To Brief",
      "summary": "Use when a dense source needs to become something decision-useful quickly.",
      "tags": [
        "source",
        "brief"
      ],
      "body": [
        [
          "Useful inputs",
          "the source material or notes, the purpose, audience, or decision this should support, any known gaps or questions that still matter"
        ],
        [
          "Suggested blocks",
          "`mode.explore` -> `core.summarize-source` -> `core.extract-insights` -> `core.research-questions` -> `core.plan-next-actions`"
        ],
        [
          "Expected outcome",
          "a compressed source summary, the most decision-relevant insights, the most useful open questions, clear next actions"
        ]
      ],
      "sourcePath": "stacks/source-to-brief.md"
    },
    {
      "section": "Stack",
      "key": "stack.stakeholder-alignment",
      "title": "Stakeholder Alignment",
      "summary": "Use when the right answer is not enough because coordination and buy-in are the real bottlenecks.",
      "tags": [
        "stakeholder",
        "alignment"
      ],
      "body": [
        [
          "Useful inputs",
          "the project, decision, or change you want to move forward, the key people or groups involved, current support, resistance, or tension signals"
        ],
        [
          "Suggested blocks",
          "`mode.explore` -> `core.stakeholder-map` -> `lens.coordination-plan` -> `lens.signaling-check` -> `core.meeting-prep` -> `core.schema.execution-brief`"
        ],
        [
          "Expected outcome",
          "a clearer stakeholder map, the main alignment risk, the most important next conversation, an execution-ready coordination plan"
        ]
      ],
      "sourcePath": "stacks/stakeholder-alignment.md"
    },
    {
      "section": "Stack",
      "key": "stack.write-critique-rewrite",
      "title": "Write, Critique, Rewrite",
      "summary": "Use when the first draft should be fast but the final draft should be sharp.",
      "tags": [
        "write",
        "critique",
        "rewrite"
      ],
      "body": [
        [
          "Useful inputs",
          "the intended audience and goal, source points, notes, or a rough draft, any constraints on length, tone, or format"
        ],
        [
          "Suggested blocks",
          "`core.write-first-draft` -> `mode.critique` -> `core.critique-argument` -> `core.rewrite-for-clarity` -> `rubric.writing-quality`"
        ],
        [
          "Expected outcome",
          "first draft, prioritized critique, stronger revision"
        ]
      ],
      "sourcePath": "stacks/write-critique-rewrite.md"
    },
    {
      "section": "Stack",
      "key": "stack.prompt-repair",
      "title": "Prompt Repair",
      "summary": "Use when a prompt is the thing you are trying to improve.",
      "tags": [
        "repair"
      ],
      "body": [
        [
          "Useful inputs",
          "the current prompt, the job the prompt should do, examples of failure, ambiguity, or weak output if available"
        ],
        [
          "Suggested blocks",
          "`mode.critique` -> `core.clarify-task` -> `core.prompt-critique` -> `core.prompt-rewrite` -> `core.prompt-compare` -> `rubric.prompt-quality`"
        ],
        [
          "Expected outcome",
          "clearer prompt intent, fewer failure modes, a tighter revision, a prompt that is easier to test and reuse"
        ]
      ],
      "sourcePath": "stacks/prompt-repair.md"
    },
    {
      "section": "Stack",
      "key": "stack.weekly-review",
      "title": "Weekly Review",
      "summary": "Use when you want to learn from a week without creating a huge ritual.",
      "tags": [
        "weekly",
        "review"
      ],
      "body": [
        [
          "Useful inputs",
          "weekly notes, outcomes, or calendar fragments, key wins, failures, or stuck points, any major decisions worth revisiting"
        ],
        [
          "Suggested blocks",
          "`mode.reflect` -> `core.weekly-review` -> `core.cause-mapping` for key failures -> `core.decision-journal-entry` for any major decision worth revisiting -> `rubric.reflection-quality`"
        ],
        [
          "Expected outcome",
          "lessons, repeated frictions, next-week focus, decisions worth tracking"
        ]
      ],
      "sourcePath": "stacks/weekly-review.md"
    }
  ],
  "featuredStacks": [
    {
      "title": "Frame an Unknown Problem",
      "description": "When you are not sure what you are actually solving. Explores breadth, frames the task, decomposes it, and surfaces uncertainty before any commitment.",
      "tags": [
        "framing",
        "clarity",
        "explore"
      ],
      "refs": [
        "mode.explore",
        "core.frame.task",
        "strategy.problem-split",
        "core.scope.frame",
        "core.guardrail.uncertainty"
      ]
    },
    {
      "title": "Make a Risky Decision",
      "description": "When real options exist and the stakes matter. Sets criteria, steelmans alternatives, audits assumptions, and captures the final choice.",
      "tags": [
        "decide",
        "rigor",
        "high-stakes"
      ],
      "refs": [
        "mode.decide",
        "core.frame.success-criteria",
        "strategy.steelman",
        "core.assumption.audit",
        "core.schema.decision-memo"
      ]
    },
    {
      "title": "Explore or Exploit",
      "description": "When the real question is whether to keep searching or commit now. Forces the tradeoff between additional information and the cost of delay, then turns the answer into an immediate move.",
      "tags": [
        "decision",
        "exploration",
        "timing"
      ],
      "refs": [
        "mode.decide",
        "core.frame.success-criteria",
        "core.explore-exploit-decision",
        "core.guardrail.uncertainty",
        "core.schema.execution-brief"
      ]
    },
    {
      "title": "Prioritize a Portfolio",
      "description": "When several good-looking bets compete for scarce resources. Defines criteria, ranks the field, and turns the winner into an execution brief.",
      "tags": [
        "prioritization",
        "portfolio",
        "focus"
      ],
      "refs": [
        "mode.decide",
        "core.frame.success-criteria",
        "core.prioritize-opportunities",
        "core.schema.execution-brief",
        "core.guardrail.uncertainty"
      ]
    },
    {
      "title": "De-Risk Before Committing",
      "description": "When a direction looks promising but the real blocker is uncertainty. Designs the cheapest credible test and makes the next checkpoint explicit.",
      "tags": [
        "experiment",
        "de-risk",
        "execution"
      ],
      "refs": [
        "mode.decide",
        "core.frame.success-criteria",
        "core.design-cheap-test",
        "core.schema.execution-brief",
        "core.guardrail.uncertainty"
      ]
    },
    {
      "title": "Pressure Test a Plan",
      "description": "Before committing to execution. Runs adversarial critique, premortem, and stress test to surface the plan's biggest vulnerabilities.",
      "tags": [
        "critique",
        "risk",
        "pre-commit"
      ],
      "refs": [
        "mode.critique",
        "strategy.premortem",
        "strategy.red-team",
        "core.assumption.audit",
        "core.stress-test-assumptions"
      ]
    },
    {
      "title": "Debug a Failure",
      "description": "When a bug, incident, or broken workflow needs a structured diagnosis. Localizes the failure, checks the boundary, and turns the next move into a concrete debug plan.",
      "tags": [
        "debugging",
        "incident",
        "diagnosis"
      ],
      "refs": [
        "mode.critique",
        "lens.debugger-loop",
        "lens.interface-contract-review",
        "lens.invariant-check",
        "core.plan-next-actions"
      ]
    },
    {
      "title": "Write and Sharpen",
      "description": "For content that needs to be good, not just done. Drafts fast, then critiques rigorously, then rewrites for clarity.",
      "tags": [
        "writing",
        "critique",
        "revision"
      ],
      "refs": [
        "core.write-first-draft",
        "mode.critique",
        "core.critique-argument",
        "core.rewrite-for-clarity",
        "rubric.writing-quality"
      ]
    },
    {
      "title": "After-Action Review",
      "description": "When an outcome exists and the risk is repeating the same mistake. Maps causes, records the decision, and checks that reflection was actually useful.",
      "tags": [
        "reflect",
        "learning",
        "retrospective"
      ],
      "refs": [
        "mode.reflect",
        "core.cause-mapping",
        "core.decision-journal-entry",
        "rubric.reflection-quality"
      ]
    },
    {
      "title": "Improve a Prompt",
      "description": "When a prompt is underperforming. Critiques the current version, rewrites it, compares variants, and checks against a quality rubric.",
      "tags": [
        "prompting",
        "iteration",
        "repair"
      ],
      "refs": [
        "mode.critique",
        "core.prompt-critique",
        "core.prompt-rewrite",
        "core.prompt-compare",
        "rubric.prompt-quality"
      ]
    },
    {
      "title": "Map Incentives",
      "description": "When behavior is not making sense or you are designing for a multi-player situation. Audits incentives, checks signals, and captures the analysis.",
      "tags": [
        "game theory",
        "incentives",
        "analysis"
      ],
      "refs": [
        "mode.explore",
        "lens.incentive-audit",
        "lens.signaling-check",
        "core.schema.decision-memo"
      ]
    },
    {
      "title": "Align Stakeholders",
      "description": "When the technical answer is not enough and alignment is the actual bottleneck. Maps stakeholders, checks coordination dynamics, and prepares the next conversation.",
      "tags": [
        "alignment",
        "stakeholders",
        "coordination"
      ],
      "refs": [
        "mode.explore",
        "core.stakeholder-map",
        "lens.coordination-plan",
        "lens.signaling-check",
        "core.meeting-prep",
        "core.schema.execution-brief"
      ]
    },
    {
      "title": "Turn Sources Into Action",
      "description": "When notes, transcripts, or dense source material need to become something decision-useful quickly. Distills the source, extracts what matters, and maps the next investigation or action.",
      "tags": [
        "research",
        "synthesis",
        "briefing"
      ],
      "refs": [
        "mode.explore",
        "core.summarize-source",
        "core.extract-insights",
        "core.research-questions",
        "core.plan-next-actions"
      ]
    },
    {
      "title": "Check for Bias",
      "description": "When a judgment or decision may be distorted. Reviews cognitive biases, steelmans alternatives, and guardrails against false certainty.",
      "tags": [
        "psychology",
        "bias",
        "rigor"
      ],
      "refs": [
        "mode.critique",
        "lens.bias-check",
        "strategy.steelman",
        "core.guardrail.disconfirming-evidence",
        "core.guardrail.uncertainty"
      ]
    }
  ]
};
